// ╔═══════════════════════════════════════╗
// ║  @Ultr                                ║
// ║  My KillZones                         ║
// ╚═══════════════════════════════════════╝

//@version=5
indicator("My KillZones (@Ultr)", shorttitle = "My Kill Z (@Ultr.)", overlay = true)

//  ════════════
//  My Killzones
//  Constants
//  ═════════

// Color
color colorZero = color.new(#0034c5, 90)
color colorFirs = color.new(#33ffac, 90)
color colorSeco = color.new(#e91e63, 75)
color colorThir = color.new(#eedd45, 90)
color colorCuar = color.new(#9598a1, 90)

// Session
string sessionNewY = "America/New_York"					// Sesion - America/New York
string sessionChig = "America/Chicago"					// Sesion - America/Chicago
string sessionArge = "America/Argentina/Buenos_Aires"	// Sesion - America/Buenos Aires
string sessionEuro = "Europe/London"					// Sesion - Europa/Londres
string sessionAsia = "Asia/Shanghai"					// Sesion - Asia/Shanghai
string sessionAust = "Australia/Sydney"					// Sesion - Asia/Sydney

// Time
string timeU0 = input.session('0730-0815:2', title="Time 1")
string timeU1 = input.session('0900-1030:1234567', title="Time 2")
string timeU2 = input.session('1100-1145:1234567', title="Time 3")
string timeU3 = input.session('1200-1300:234567', title="Time 4")
string timeU4 = input.session('1400-1430:234567', title="Time 5")

//  ════════════
//  My Killzones
//  Inputs - Options
//  ══════

string optionSession = input.string(defval="Chicago", title="Sesión", options = ["New York", "Chicago", "Londres", "Shanghai", "Sydney", "Argentina"])

//  ════════════
//  My Killzones
//  Switch
//  ══════

//  sesion
string switchSession = switch optionSession
	// "Chicago"	=> sessionChig
	"New York"	=> sessionNewY
	"Londres"	=> sessionEuro
	"Shanghai"	=> sessionAsia
	"Sydney"	=> sessionAust
	"Argentina"	=> sessionArge
	=> sessionChig

//  ════════════
//  My Killzones
//  Display
//  ═══════
areaZero = time(timeframe.period, timeU0, switchSession)
areaFirs = time(timeframe.period, timeU1, switchSession)
areaSeco = time(timeframe.period, timeU2, switchSession)
areaThir = time(timeframe.period, timeU3, switchSession)
areaCuar = time(timeframe.period, timeU4, switchSession)

ifZero = na(areaZero) ? na : colorZero
ifFirs = na(areaFirs) ? na : colorFirs
ifSeco = na(areaSeco) ? na : colorSeco
ifThir = na(areaThir) ? na : colorThir
ifCuar = na(areaCuar) ? na : colorCuar

bgcolor(ifZero, title = 'Pre Mercado')
bgcolor(ifFirs, title = 'Inicio Sesión')
bgcolor(ifSeco, title = 'Sesion Continuada')
bgcolor(ifThir, title = 'Latelalización')
bgcolor(ifCuar, title = 'Post Mercado')
